name: ServerCore
main: me.haer0248.ServerCore.Main
version: 1.0.0
api-version: 1.16
author: Haer0248
description: Anonymous Premium Server Core.
commands:
    back:
        description: Back last death location.
    spawn:
        description: Back server spawn.
    list:
        description: Display server online player.
    m:
        description: Wisper player.
    msg:
        description: Wisper player.
    r:
        description: Reply player.
    reply:
        description: Reply player.
    bed:
        description: Back bed location.
    bc:
        description: Boardcast.
        permission: servercore.admin
    setspawn:
        description: Set server spawn.
        permission: servercore.admin
    fly:
        description: Enable/Disable fly mode.
permission:
    servercore.admin:
        default: op
        description: Access all admin commands.